apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  mysql-root-password: {{ .Values.mysql.credentials.rootPassword | quote }}
  mysql-password: {{ .Values.mysql.credentials.password | quote }}
